<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Laravel\Passport\Client;

class Passport extends Client
{
    public function skipsAuthorization()
    {
        return false;
//        return parent::skipsAuthorization(); // TODO: Change the autogenerated stub
    }
}
